package employe;
import javax.swing.JFrame;

import javax.swing.JPanel;
import java.awt.Color;
import java.awt.Graphics;
import static java.lang.Class.forName;
import java.nio.charset.Charset;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class jemployehome extends javax.swing.JInternalFrame{
    Myconnection  cnx=new Myconnection();
    
    
    /**
     * Creates new form 
     */
    public jemployehome() throws ClassNotFoundException, SQLException {
        initComponents();
                jTDateNais.setDate(new Date());
                jTDateRecru.setDate(new Date());
    //Définit un titre pour notre fenêtre
    this.setTitle("Acceuil employe");
    
    this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    //Et enfin, la rendre visible        
    this.setVisible(true);
    jComboBoxSex.addItem("M");
     jComboBoxSex.addItem("F");
     
    
     Connection c=null;
     Statement s=null;
     ResultSet rs=null;
     String nomserv=null;
     String nomdiplo=null;
              
           try
           {
               c=cnx.getConnexion();
               s=c.createStatement();
            String sql="SELECT NOM_SERVICE FROM service";
                    rs=s.executeQuery(sql);
                    
                            while(rs.next())
                            {
                                nomserv=rs.getString("NOM_SERVICE");
                                jComboBoxserv.addItem(nomserv);
                            }
               /*String sqlS1="SELECT NOM_DIPLOME FROM diplome";
                rs=s.executeQuery(sqlS1);
                
                             while(rs.next())
                            {
                                nomdiplo=rs.getString("NOM_DIPLOME");
                                jComboBoxDiplo.addItem(nomdiplo);
                            }
                       */      
                             DefaultListModel model = new DefaultListModel();
                             
       model.addElement("Selectionner les diplomes");
       
                String  sqlS1="SELECT NOM_DIPLOME_ARAB FROM diplome";
                  
                rs=s.executeQuery(sqlS1);
                int taille=0;
                             while(rs.next())
                            {
                                nomdiplo=rs.getString("NOM_DIPLOME_ARAB");
                                model.addElement((String)nomdiplo);
                                taille++;
                            } 
                 jList1.setModel(model);
                 jList1.setVisibleRowCount(taille);
             
                    
           }
           catch(SQLException e) { 
      JOptionPane.showMessageDialog(this, "Verifiez vos données"+e.getMessage());
            } catch (ClassNotFoundException ex) { 
            Logger.getLogger(jemployehome.class.getName()).log(Level.SEVERE, null, ex);
        } 
    
    
    }
    
    public class Panneau extends JPanel { 
  public void paintComponent(Graphics g){
    //Vous verrez cette phrase chaque fois que la méthode sera invoquée
   
    g.fillOval(20, 20, 75, 75);
  }               
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jListemp = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextNom = new javax.swing.JTextField();
        jTextPrenom = new javax.swing.JTextField();
        jTextMatricule = new javax.swing.JTextField();
        jTextCin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextNoma = new javax.swing.JTextField();
        jTextPrenoma = new javax.swing.JTextField();
        jComboBoxserv = new javax.swing.JComboBox<>();
        jComboBoxSex = new javax.swing.JComboBox<>();
        jTDateNais = new com.toedter.calendar.JDateChooser();
        jTDateRecru = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jTextnote = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setText("jLabel7");

        jToggleButton1.setText("jToggleButton1");

        jScrollPane3.setViewportView(jEditorPane1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sign-Add-icon.png"))); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/modifier.gif"))); // NOI18N
        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/supprimer.gif"))); // NOI18N
        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sortie.gif"))); // NOI18N
        jButton4.setText("fermer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/printer.png"))); // NOI18N
        jButton7.setText("Imprimer");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(30, 30, 30)
                .addComponent(jButton3)
                .addGap(26, 26, 26)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nom", "Prenom", "Nom arab", "Prenom arab", "Service", "Date naissance", "Date recrutement", "Sex", "CIN", "Matricule", "Diplomes", "Note"
            }
        ));
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(10).setResizable(false);
            jTable2.getColumnModel().getColumn(11).setResizable(false);
        }

        jListemp.setBackground(new java.awt.Color(255, 255, 0));
        jListemp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jListemp.setForeground(new java.awt.Color(51, 51, 0));
        jListemp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/all_new.png"))); // NOI18N
        jListemp.setText("liste des employés");
        jListemp.setActionCommand("liste des employés");
        jListemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListempActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(jListemp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jListemp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "informations employé", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Nom");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Prenom");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Cin");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Matricule");

        jTextNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Sex");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("Service");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setText("Date naissance");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 102));
        jLabel9.setText("Date recrutement");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 204));
        jLabel10.setText("إسم العائلي ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 204));
        jLabel11.setText("إسم الشخصي");

        jComboBoxserv.setBackground(new java.awt.Color(153, 153, 0));
        jComboBoxserv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectionner service" }));
        jComboBoxserv.setName("jComboBoxserv"); // NOI18N
        jComboBoxserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxservActionPerformed(evt);
            }
        });

        jComboBoxSex.setBackground(new java.awt.Color(153, 153, 0));
        jComboBoxSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectionner Sex" }));

        jTDateNais.setDateFormatString("yyyy-MM-dd");

        jTDateRecru.setDateFormatString("yyyy-MM-dd");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 0, 102));
        jLabel12.setText("Diplome");

        jButton5.setBackground(new java.awt.Color(0, 255, 51));
        jButton5.setText("+");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/view-refresh-4.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(jList1);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 51));
        jLabel13.setText("Note");

        jTextnote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextnoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jTDateRecru, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addComponent(jButton5))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jComboBoxserv, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTDateNais, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jTextNom))))
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jTextnote, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3))
                            .addGap(21, 21, 21)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextCin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxSex, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextPrenoma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jTextNoma, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jTextNoma, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPrenoma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(jComboBoxserv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTDateNais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextCin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTDateRecru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel12)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextnote)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(43, 43, 43))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("jacceuil");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Connection c=null;
              Statement s=null;
              ResultSet rs=null;
          int row= jTable2.getSelectedRow();
         if(row >= 0)      
         {
       String matricule1=jTable2.getValueAt(row, 9).toString();
        
       try { 
          c=cnx.getConnexion();
         // PreparedStatement ps1 = c.prepareStatement(sqlS);
         int rep= JOptionPane.showConfirmDialog(rootPane, " Vous voulez vraiment supprimer");
         
         if(rep==0)
         {
                       String sqlS1="DELETE FROM avoir WHERE MATRICULE='"+ matricule1+"'";
           PreparedStatement ps = c.prepareStatement(sqlS1);
           ps.executeUpdate() ;
          String sqlS2="DELETE FROM grade_durant WHERE MATRICULE='"+ matricule1+"'";
           ps = c.prepareStatement(sqlS2);
           ps.executeUpdate() ;
           String sqlS="DELETE FROM employe WHERE MATRICULE='"+ matricule1+"'";
           ps = c.prepareStatement(sqlS);
            
                     ps.executeUpdate() ;  
                    
                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
     
                model.removeRow(row);
         }
         } catch (ClassNotFoundException ex) { 
            Logger.getLogger(jemployehome.class.getName()).log(Level.SEVERE, null, ex);
        }   catch (SQLException ex) { 
                Logger.getLogger(jemployehome.class.getName()).log(Level.SEVERE, null, ex);
            } 
         }else
             
         JOptionPane.showMessageDialog(this, "Vous devez selectionner ");
            
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Connection c=null;
              Statement s=null;
              ResultSet rs=null;
         String nomserv= jComboBoxserv.getSelectedItem().toString();
        String nom=jTextNom.getText();
        String prenom=jTextPrenom.getText();
         String noma= new String(jTextNoma.getText().getBytes(),Charset.forName("UTF-8"));
        String prenoma=jTextPrenoma.getText();   
        //JOptionPane.showMessageDialog(this,noma+" "+prenoma);
          String datenaissance=sdf.format(jTDateNais.getDate());
          String daterecrutement=sdf.format(jTDateRecru.getDate());
         String sex= (String) jComboBoxSex.getSelectedItem();
         String cin=jTextCin.getText();
         String matricule=jTextMatricule.getText();
         int note=Integer.parseInt(jTextnote.getText());
         // String diplome=jComboBoxDiplo.getSelectedItem().toString();
       //   String listediplome[]=(String[]) jList1.getSelectedValuesList().toArray();
         int idservice=0;
         String diplo=null;
         //jList1.getSelectedValuesList().get(0);
        
        try {                              
            c=cnx.getConnexion();
           String sqlS="SELECT ID_SERVICE  FROM service where NOM_SERVICE='"+nomserv+"'";
            s= c.createStatement();
            rs=s.executeQuery(sqlS);
                 rs.first();
        idservice=rs.getInt("ID_SERVICE");
            
       
        
            
         
        
           String sql="INSERT INTO employe(ID_SERVICE,NOM_EMPLOYE,PRENOM_EMPLYE,NOMARAB,PRENOMARAB,DATE_NAISSANCE,DATE_RECRUTEMENT,SEX,CIN,MATRICULE,note) values(?,?,?,?,?,?,?,?,?,?,?)";  
           PreparedStatement pst= c.prepareStatement(sql);
           
           
           pst.setInt(1,idservice);
            pst.setString(2,nom);
            pst.setString(3,prenom);
            pst.setString(4,noma);
            pst.setString(5,prenoma);
            pst.setString(6,datenaissance);
            pst.setString(7,daterecrutement);
             pst.setString(8,sex);
             pst.setString(9,cin);
             pst.setString(10,matricule);
             pst.setInt(11,note);
            
               pst.execute();
               
               int tListe =jList1.getSelectedValuesList().size();
               for(int i=0 ; i<tListe; i++)
               {
                 String  sqlS1="SELECT ID_DIPLOME FROM diplome where NOM_DIPLOME='"+jList1.getSelectedValuesList().get(i)+"' ";
            s= c.createStatement();
            rs=s.executeQuery(sqlS1);
                 rs.first();
           rs.getString("ID_DIPLOME");
                sql="INSERT INTO avoir(MATRICULE,ID_DIPLOME) values(?,?)";  
            pst= c.prepareStatement(sql);
           
           
           pst.setString(1,matricule);
            pst.setString(2,rs.getString("ID_DIPLOME"));
            pst.execute();
               }   
         JOptionPane.showMessageDialog(this, "Vous avez bien inserer");
               
       }
       catch(SQLException e) { 
      JOptionPane.showMessageDialog(this, "Verifiez vos données"+e.getMessage());
            } catch (ClassNotFoundException ex) { 
            Logger.getLogger(jemployehome.class.getName()).log(Level.SEVERE, null, ex);
        } 
          jTextNom.setText(null);
        jTextPrenom.setText(null);
        jTextNoma.setText(null);
       jTextPrenoma.setText(null);   
          
        jTextCin.setText(null);
        jTextMatricule.setText(null);
        jTextnote.setText(" ");
        
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int row= jTable2.getSelectedRow();
       String n=null;
      
         if(row >= 0)
         {  String nom=(jTable2.getValueAt(row, 0)).toString();
        String prenom=(jTable2.getValueAt(row, 1)).toString();
         String noma=(jTable2.getValueAt(row, 2)).toString();
        String prenoma=(jTable2.getValueAt(row, 3)).toString();
        //String nomserv= (jTable2.getValueAt(row, 4)).toString();
          String datenaissance=(jTable2.getValueAt(row, 5)).toString();
          String daterecrutement=(jTable2.getValueAt(row, 6)).toString();
        String sex= (jTable2.getValueAt(row, 7)).toString();
         String cin=(jTable2.getValueAt(row, 8)).toString();
         String matricule1=jTable2.getValueAt(row, 9).toString();
        n=jTable2.getValueAt(row, 11).toString();
        int note=Integer.parseInt(n);
           jModemp mod =new jModemp(nom, prenom,noma, prenoma, datenaissance, daterecrutement, sex, cin, matricule1,note);     
       // jacceuil acc=new jacceuil();
        //acc.setjPapp(mod);
        //this.getParent().removeAll();
        
   
      this.getParent().add(mod);
      this.dispose();
        mod.show();
         }
         else
         {
        JOptionPane.showMessageDialog(this, "Vous devez selectionner ");
         }
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
      
        dispose();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jListempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListempActionPerformed
        // TODO add your handling code here:
       DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
       
       while(jTable2.getRowCount()>0) // pour supprimer l'encien table
            model.removeRow(0);
       
       Connection c=null;
              Statement s=null;
              ResultSet rs=null;
              Statement s1=null;
              Statement s2=null;
              ResultSet rs1=null;
              ResultSet rs2=null;
              String serv=null;
             String matric=null;
              String matricule=jTextMatricule.getText();
              
              try { 
            c=cnx.getConnexion();
            String sqlS="SELECT * FROM employe";
            s= c.createStatement();
            rs=s.executeQuery(sqlS);
            
            
             while(rs.next())
                    { 
                        sqlS="SELECT NOM_SERVICE,ID_SERVICE FROM service WHERE ID_SERVICE='"+rs.getInt("ID_SERVICE")+"'";
                    s2=c.createStatement();
                    rs2=s2.executeQuery(sqlS);
                    rs2.first();
                    String service=rs2.getString("NOM_SERVICE");
                        
                    sqlS="SELECT  NOM_DIPLOME_ARAB FROM  diplome,avoir WHERE diplome.ID_DIPLOME= avoir.ID_DIPLOME AND avoir.MATRICULE='"+rs.getString("MATRICULE")+"'";
                    s1= c.createStatement();
                     rs1=s1.executeQuery(sqlS);
                     String d=" ";
                     
                    while( rs1.next())
                    {
                     
                     d=d+"_"+rs1.getString("NOM_DIPLOME_ARAB");
                    }
                  model.addRow(new Object[]{rs.getString("NOM_EMPLOYE"),rs.getString("PRENOM_EMPLYE"),rs.getString("NOMARAB"),rs.getString("PRENOMARAB"),service,rs.getString("DATE_NAISSANCE"),rs.getString("DATE_RECRUTEMENT"),rs.getString("SEX"),rs.getString("CIN"),rs.getString("MATRICULE"),d,rs.getInt("note")});

                    }
            
              }
              catch(SQLException e) { 
      JOptionPane.showMessageDialog(this, "Verifiez vos données"+e.getMessage());
            } catch (ClassNotFoundException ex) { 
            Logger.getLogger(jemployehome.class.getName()).log(Level.SEVERE, null, ex);
        } 
         
    }//GEN-LAST:event_jListempActionPerformed

    private void jComboBoxservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxservActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBoxservActionPerformed

    private void jTextNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jAjouteDiplo d =new jAjouteDiplo();
       this.getParent().add(d);
       // this.add(d);
     // this.dispose();
        d.show();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
          DefaultListModel model = new DefaultListModel();
          
        Connection c=null;
     Statement s=null;
     ResultSet rs=null;
     String nomserv=null;
     String nomdiplo=null;
     model.removeAllElements();
   
      
    model.addElement("Selectionner les diplomes");
         try
           {
               c=cnx.getConnexion();
               s=c.createStatement();
           
                
                             
       
       
                String  sqlS1="SELECT NOM_DIPLOME_ARAB FROM diplome";
                  
                rs=s.executeQuery(sqlS1);
                int taille=0;
                             while(rs.next())
                            {
                                nomdiplo=rs.getString("NOM_DIPLOME_ARAB");
                                model.addElement((String)nomdiplo);
                                taille++;
                            } 
                 jList1.setModel(model);
                 jList1.setVisibleRowCount(taille);
                    
           }
           catch(SQLException e) { 
      JOptionPane.showMessageDialog(this, "Verifiez vos données"+e.getMessage());
            } catch (ClassNotFoundException ex) { 
            Logger.getLogger(jemployehome.class.getName()).log(Level.SEVERE, null, ex);
        } 
    
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextnoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextnoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextnoteActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Commune Ait Melloul \n Liste des employés \n ");
        
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try {
            jTable2.print(JTable.PrintMode.FIT_WIDTH, header, footer);

        } catch (java.awt.print.PrinterException e) {
            System.err.format("Erreur d'impression ", e.getMessage());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxSex;
    private javax.swing.JComboBox<String> jComboBoxserv;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JButton jListemp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser jTDateNais;
    private com.toedter.calendar.JDateChooser jTDateRecru;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextCin;
    private javax.swing.JTextField jTextMatricule;
    private javax.swing.JTextField jTextNom;
    private javax.swing.JTextField jTextNoma;
    private javax.swing.JTextField jTextPrenom;
    private javax.swing.JTextField jTextPrenoma;
    private javax.swing.JTextField jTextnote;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
