/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employe;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mounsif elkhiyar
 */
public class jModemp extends javax.swing.JInternalFrame {
 Myconnection  cnx=new Myconnection();
 employe E=null;
 
 
    /**cnx
     * Creates new form jModemp
     */

    public jModemp(String nom, String prenom, String nom_arab, String prenom_arab, String datenaissance, String daterecrutement, String sex, String cin, String matricul,int note) {
        initComponents();
             E = new employe( nom,  prenom,  nom_arab,  prenom_arab,  datenaissance,  daterecrutement,  sex, cin,  matricul,note);

     Connection c=null;
     Statement s=null;
         ResultSet rs=null;

     String nomserv=null;
     //String nomdiplo=null;
     
      jTextNom.setText(this.E.getNom());
     jTextPrenom.setText(this.E.getPrenom());
     jTextNoma.setText(this.E.getNom_arab());
     jTextPrenoma.setText(this.E.getPrenom_arab());
   //  jComboBoxserv.setSelectedItem(nomserv);
     jTextDatenaiss.setText(this.E.getDatenaissance());
     jTextDaterecru.setText(this.E.getDaterecrutement());
     jComboBoxSex.setSelectedItem(this.E.getSex());
     jTextCin.setText(this.E.getCin());
     jTextMatricule.setText(this.E.getMatricule());
     jTextnote.setText(String.valueOf(this.E.getnote()));
     jTextMatricule.setEditable(false);
      try
           {
               c=cnx.getConnexion();
               s=c.createStatement();
             
            String sql="SELECT NOM_SERVICE FROM service";
                    rs=s.executeQuery(sql);
                    
            
                            while(rs.next())
                            {
                                nomserv=rs.getString("NOM_SERVICE");
                                jComboBoxserv.addItem(nomserv);
                            }
             /* String sql1="SELECT NOM_DIPLOME FROM diplome";
                    rs=s.executeQuery(sql1);
                    
            
                            while(rs.next())
                            {
                                nomdiplo=rs.getString("NOM_DIPLOME");
                                jComboBoxDiplo.addItem(nomdiplo);
                            }              
                            */
          
  
               sql="SELECT NOM_SERVICE FROM service WHERE ID_SERVICE IN (SELECT ID_SERVICE FROM employe WHERE MATRICULE='"+this.E.getMatricule()+"')";
               //jTextNom.setText(sql);
          
                    rs=s.executeQuery(sql);
                    
            
                            rs.first();
                           // int x=0;
                               nomserv=rs.getString("NOM_SERVICE");
                               // x=rs.getInt("ID_SERVICE");
                               jComboBoxserv.setSelectedItem(nomserv);
                               //jTextNom.setText(nomserv);
                     
           }
           catch(SQLException e) { 
      JOptionPane.showMessageDialog(this, "Verifiez vos données"+e.getMessage());
            } catch (ClassNotFoundException ex) { 
            Logger.getLogger(jemployehome.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextNom = new javax.swing.JTextField();
        jTextPrenom = new javax.swing.JTextField();
        jTextMatricule = new javax.swing.JTextField();
        jTextCin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextNoma = new javax.swing.JTextField();
        jTextPrenoma = new javax.swing.JTextField();
        jComboBoxserv = new javax.swing.JComboBox<>();
        jComboBoxSex = new javax.swing.JComboBox<>();
        jTextDatenaiss = new javax.swing.JTextField();
        jTextDaterecru = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextnote = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jAppliquemod = new javax.swing.JButton();
        jretourmod = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informations employé", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Nom");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Prenom");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Cin");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Matricule");

        jTextNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Sex");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("Service");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setText("Date naissance");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 102));
        jLabel9.setText("Date recrutement");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 204));
        jLabel10.setText("إسم العائلي ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 204));
        jLabel11.setText("إسم الشخصي");

        jTextPrenoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPrenomaActionPerformed(evt);
            }
        });

        jComboBoxserv.setBackground(new java.awt.Color(153, 153, 0));
        jComboBoxserv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectionner service" }));
        jComboBoxserv.setName("jComboBoxserv"); // NOI18N
        jComboBoxserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxservActionPerformed(evt);
            }
        });

        jComboBoxSex.setBackground(new java.awt.Color(153, 153, 0));
        jComboBoxSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selectionner Sex", "M", "F" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Note");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextDatenaiss, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxserv, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextPrenoma, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextNoma, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel11))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(jLabel10))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jComboBoxSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextCin, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jTextDaterecru, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jTextnote, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextNoma, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPrenoma, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSex, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxserv, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDatenaiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jTextCin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jTextDaterecru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextnote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 0)));

        jAppliquemod.setBackground(new java.awt.Color(0, 204, 102));
        jAppliquemod.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jAppliquemod.setText("Appliquer");
        jAppliquemod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAppliquemodActionPerformed(evt);
            }
        });

        jretourmod.setBackground(new java.awt.Color(0, 204, 102));
        jretourmod.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jretourmod.setText("retour");
        jretourmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jretourmodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jAppliquemod)
                .addGap(107, 107, 107)
                .addComponent(jretourmod)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jretourmod)
                    .addComponent(jAppliquemod))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleName("jacceuil");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jretourmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jretourmodActionPerformed
        try {
            // TODO add your handling code here:

            jemployehome f  = new jemployehome();
             this.getParent().add(f);
      this.dispose();
        f.show();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jModemp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(jModemp.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jretourmodActionPerformed

    private void jAppliquemodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAppliquemodActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Connection c=null;
        Statement s=null;
        ResultSet rs=null;

        String nomserv= jComboBoxserv.getSelectedItem().toString();
        String nom=jTextNom.getText();
        String prenom=jTextPrenom.getText();
        String noma=jTextNoma.getText();
        String prenoma=jTextPrenoma.getText();
        String datenaissance=jTextDatenaiss.getText();
       
          String daterecrutement=jTextDaterecru.getText();
        String sex= (String) jComboBoxSex.getSelectedItem();
        String cin=jTextCin.getText();
        String matricule1=jTextMatricule.getText();
        int note=Integer.parseInt(jTextnote.getText());
        int idservice=0;

        try {
            c=cnx.getConnexion();
            String sql="SELECT ID_SERVICE  FROM service where NOM_SERVICE='"+nomserv+"'";
            s= c.createStatement();
            rs=s.executeQuery(sql);
            rs.first();
            idservice=rs.getInt("ID_SERVICE");
           if(nom.equalsIgnoreCase("") || prenom.equalsIgnoreCase("")  )
           {
            JOptionPane.showMessageDialog(this, "Vous devez remplir tous les champs");
           }
           else
           {
            String sqlS="UPDATE employe SET ID_SERVICE=?,NOM_EMPLOYE=?,PRENOM_EMPLYE=?,NOMARAB=?,PRENOMARAB=?,DATE_NAISSANCE=?,DATE_RECRUTEMENT=?,SEX=?,CIN=?,note=? WHERE MATRICULE='"+this.E.getMatricule()+"'" ;
            PreparedStatement pst= c.prepareStatement(sqlS);
            pst.setInt(1,idservice);
            pst.setString(2,nom);
            pst.setString(3,prenom);
            pst.setString(4,noma);
            pst.setString(5,prenoma);
            pst.setString(6,datenaissance);
            pst.setString(7,daterecrutement);
            pst.setString(8,sex);
            pst.setString(9,cin);
            pst.setInt(10,note);
            pst.executeUpdate();        
            JOptionPane.showMessageDialog(this, "Vous avez bien modifier");
           }
            
        }

        catch(SQLException e) {
            JOptionPane.showMessageDialog(this, "Verifiez vos données"+e.getMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(jemployehome.class.getName()).log(Level.SEVERE, null, ex);
        }

       

    }//GEN-LAST:event_jAppliquemodActionPerformed

    private void jComboBoxservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxservActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxservActionPerformed

    private void jTextNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomActionPerformed

    private void jTextPrenomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPrenomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPrenomaActionPerformed

    /**
     * @param args the command line arguments
     */
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAppliquemod;
    private javax.swing.JComboBox<String> jComboBoxSex;
    private javax.swing.JComboBox<String> jComboBoxserv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextCin;
    private javax.swing.JTextField jTextDatenaiss;
    private javax.swing.JTextField jTextDaterecru;
    private javax.swing.JTextField jTextMatricule;
    private javax.swing.JTextField jTextNom;
    private javax.swing.JTextField jTextNoma;
    private javax.swing.JTextField jTextPrenom;
    private javax.swing.JTextField jTextPrenoma;
    private javax.swing.JTextField jTextnote;
    private javax.swing.JButton jretourmod;
    // End of variables declaration//GEN-END:variables

    void setemploye(String nom, String prenom, String noma, String prenoma, String datenaissance, String daterecrutement, String sex, String cin, int matricule1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
