/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employe;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mounsif elkhiyar
 */
public class jRecherchegeneral extends javax.swing.JInternalFrame {
Myconnection cnx = new Myconnection();
    String datedebut=null;
    int idgrade=0;
    int idechellon=0;
    String gradeact=null;
    String echellon=null;
    String indice=null;
    String annee=null;
    String matricule=null;
    String datereclasement=null;
    String dateeffectgrade=null;
    /**
     * Creates new form jRecherchegrade
     */
    public jRecherchegeneral() {
        initComponents();
        Connection c=null;
        Statement s=null;
        ResultSet rs=null;
        String gradeact=null;
        String echelo=null;
        String indi=null;
        
            try {
                c=cnx.getConnexion();
            String sqlS="SELECT GRADE_ACTUEL FROM grade";
            
                s= c.createStatement();
            
            rs=s.executeQuery(sqlS);
            while(rs.next())
            {
                gradeact=rs.getString("GRADE_ACTUEL");
                                jComboBoxgradeact.addItem(gradeact);
            }
            
             
             sqlS="SELECT ECHELLON,indice FROM echellon";
            
                s= c.createStatement();
            
            rs=s.executeQuery(sqlS);
            while(rs.next())
            {
                echelo=rs.getString("ECHELLON");
                indi= rs.getString("indice");
                
                                jComboBoxechellon.addItem(echelo+" avec indice "+indi);
            }
            
          
            
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(jacceuilGrade.class.getName()).log(Level.SEVERE, null, ex);
            }
                catch (SQLException ex) {
                Logger.getLogger(jacceuilGrade.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jComboBoxgradeact = new javax.swing.JComboBox<>();
        jComboBoxechellon = new javax.swing.JComboBox<>();
        jTextDateeffect = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButtonrecherche = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel8.setBackground(new java.awt.Color(204, 255, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recherche d'un employé", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(153, 51, 0))); // NOI18N

        jComboBoxgradeact.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "selectionner grade" }));

        jComboBoxechellon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "selectionner echellon" }));

        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("Grade actuel");

        jLabel12.setForeground(new java.awt.Color(0, 153, 153));
        jLabel12.setText("echellon");

        jLabel13.setForeground(new java.awt.Color(0, 153, 153));
        jLabel13.setText("année d'effect grade");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxgradeact, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxechellon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextDateeffect, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxgradeact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxechellon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextDateeffect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 204, 0));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sortie.gif"))); // NOI18N
        jButton8.setText("fermer");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Matricule", "nom", "prenom", "grade actuel", "Date effect", "echellon", "indice", "Dare reclassement"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 153, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/printer.png"))); // NOI18N
        jButton1.setText("Imprimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonrecherche.setBackground(new java.awt.Color(0, 204, 0));
        jButtonrecherche.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonrecherche.setForeground(new java.awt.Color(255, 153, 153));
        jButtonrecherche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/recherche.gif"))); // NOI18N
        jButtonrecherche.setText("recherche");
        jButtonrecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonrechercheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jButtonrecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonrecherche)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonrechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonrechercheActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();

        while(jTable2.getRowCount()>0) // pour supprimer l'encien table
        model.removeRow(0);
        
         Connection c=null;
        Statement s=null;
        ResultSet rs=null;
                 ResultSet rs1=null;
                 int idgradeactu=0;

                   gradeact= jComboBoxgradeact.getSelectedItem().toString();
                   echellon=jComboBoxechellon.getSelectedItem().toString();
                
                  String indice=echellon.substring(echellon.lastIndexOf(' ')+1,echellon.length());
                    
                   dateeffectgrade=jTextDateeffect.getText();
       int gradeactindice= jComboBoxgradeact.getSelectedIndex();
              int     echellonindice=jComboBoxechellon.getSelectedIndex();
            
         
              /*JOptionPane.showMessageDialog(this, jComboBoxgradeact.getSelectedIndex());
        JOptionPane.showMessageDialog(this, echellon);*/
             try {
                if(gradeactindice!=0)
                {
                    c=cnx.getConnexion();
             
                 String sqlS="SELECT ID_GRADE  FROM grade where GRADE_ACTUEL='"+gradeact+"'";
            s= c.createStatement();
            rs=s.executeQuery(sqlS);
                 rs.first();
        idgradeactu=rs.getInt("ID_GRADE");
                
        if(echellonindice!=0)
        {
          sqlS="SELECT ID_ECHELLON  FROM echellon where indice='"+indice+"'";
            s= c.createStatement();
            rs=s.executeQuery(sqlS);
                 rs.first();
        idechellon=rs.getInt("ID_ECHELLON"); 
        }
        else
        {
            idechellon=0;
        }
        if(idechellon!=0 )
                {
                    sqlS="SELECT ID_ECHELLON  FROM echellon where indice='"+indice+"'";
            s= c.createStatement();
            rs=s.executeQuery(sqlS);
                 rs.first();
            idechellon=rs.getInt("ID_ECHELLON"); 
                 
                  sqlS="SELECT MATRICULE,NOM_EMPLOYE,PRENOM_EMPLYE,ID_GRADE,ID_ECHELLON,date_reclassement,date_effectgrade FROM employe WHERE ID_ECHELLON='"+idechellon+"' AND ID_GRADE='"+idgradeactu+"' AND date_effectgrade like '"+dateeffectgrade+"%'";
                } else
        {
             sqlS="SELECT MATRICULE,NOM_EMPLOYE,PRENOM_EMPLYE,ID_GRADE,ID_ECHELLON,date_reclassement,date_effectgrade FROM employe WHERE ID_GRADE='"+idgradeactu+"' AND date_effectgrade like '"+dateeffectgrade+"%'";
        }
        s= c.createStatement();
                    rs=s.executeQuery(sqlS);
                     
                while(rs.next())
                {
                    idechellon=rs.getInt("ID_ECHELLON");
                     idgrade=rs.getInt("ID_GRADE");
                  
                  if(idechellon!=0 ) 
                  {
                    sqlS="SELECT ECHELLON,INDICE FROM echellon WHERE  ID_ECHELLON='"+idechellon+"'";
                s= c.createStatement();
                rs1=s.executeQuery(sqlS);
                rs1.first();
                echellon=rs1.getString("ECHELLON");
                indice=rs1.getString("INDICE");
                }else
                  {
                      echellon="";
                  
                  }
                 sqlS="SELECT GRADE_ACTUEL,ECHEL FROM grade WHERE  ID_GRADE='"+idgrade+"'";
                s= c.createStatement();
                rs1=s.executeQuery(sqlS);
                rs1.first();
                gradeact=rs1.getString("GRADE_ACTUEL");
                  
                  
                  
                       model.addRow(new Object[]{rs.getString("MATRICULE"),rs.getString("NOM_EMPLOYE"),rs.getString("PRENOM_EMPLYE"),gradeact,rs.getString("date_effectgrade"),echellon,indice,rs.getString("date_reclassement")});
   
                }
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Vous devez selectionner un grade");
                }
                    
                 
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(jacceuilGrade.class.getName()).log(Level.SEVERE, null, ex);
             } catch (SQLException ex) {
            Logger.getLogger(jacceuilGrade.class.getName()).log(Level.SEVERE, null, ex);
}
         
          /*
             try {
                 c=cnx.getConnexion();
                
        
                 String sqlS="SELECT MATRICULE,NOM_EMPLOYE,PRENOM_EMPLYE,ID_GRADE,date_reclassement,date_effectgrade FROM employe WHERE date_effectgrade like '"+dateeffectgrade+"%' ";
                  s= c.createStatement();
                    rs=s.executeQuery(sqlS);
                     
                while(rs.next())
                {
                    dateeffectgrade=rs.getString("date_effectgrade");
                  
                 if(dateeffectgrade!=null) 
                  {
                    String sql="SELECT GRADE_ACTUEL,ECHEL FROM grade WHERE  ID_GRADE='"+idgrade+"'";
                s= c.createStatement();
                rs1=s.executeQuery(sql);
                rs1.first();
                gradeact=rs1.getString("GRADE_ACTUEL");
                
                  }
                  else
                  {
                      gradeact="";
                      
                  }
                  
                       model.addRow(new Object[]{rs.getString("MATRICULE"),rs.getString("NOM_EMPLOYE"),rs.getString("PRENOM_EMPLYE"),gradeact,rs.getString("date_effectgrade"),echellon,rs.getString("date_reclassement")});
   
                }
         
                    
                 
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(jacceuilGrade.class.getName()).log(Level.SEVERE, null, ex);
             } catch (SQLException ex) {
            Logger.getLogger(jacceuilGrade.class.getName()).log(Level.SEVERE, null, ex);
}    */
          
             

    }//GEN-LAST:event_jButtonrechercheActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Commune Ait Melloul \n Liste des grades rechercher \n ");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try {
            jTable2.print(JTable.PrintMode.FIT_WIDTH, header, footer);

        } catch (java.awt.print.PrinterException e) {
            System.err.format("Erreur d'impression ", e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonrecherche;
    private javax.swing.JComboBox<String> jComboBoxechellon;
    private javax.swing.JComboBox<String> jComboBoxgradeact;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextDateeffect;
    // End of variables declaration//GEN-END:variables
}
